[package]
name = "Timetable_for_development"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.33.2"
egui = "0.33.2"
serde = {version = "1.0", features = ["derive"]}
serde_json = "1.0.145"
postgres = "0.19.12"
r2d2 = "0.8.10"
r2d2_postgres = "0.18.2"
dotenv = "0.15"
dotenvy = "0.15.7"